#include "common.h"

namespace profiler {

void output_yaml() {
    auto& r = results();

    printf("# Auto-generated by cpp-perf profiler\n");

    // Emit each section
    for (auto& [section, kvs] : r) {
        printf("\n%s:\n", section.c_str());
        for (auto& [key, val] : kvs) {
            if (val == (int)val)
                printf("  %s: %d\n", key.c_str(), (int)val);
            else
                printf("  %s: %.1f\n", key.c_str(), val);
        }
    }
}

} // namespace profiler
