#!/usr/bin/env python3
from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path

try:
    from .duckdb_common import (
        BUILD_COMMAND,
        build_capability_payload,
        emit_payload,
        relative_to_repo,
        select_benchmark_for_target,
        source_metrics,
        write_json,
    )
except ImportError:
    from duckdb_common import (  # type: ignore
        BUILD_COMMAND,
        build_capability_payload,
        emit_payload,
        relative_to_repo,
        select_benchmark_for_target,
        source_metrics,
        write_json,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare a DuckDB benchmark case for the campaign controller.")
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--target", required=True)
    parser.add_argument("--case-dir", required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    target_path = Path(args.target).resolve()
    case_dir = Path(args.case_dir).resolve()
    case_dir.mkdir(parents=True, exist_ok=True)

    relative_target_path = relative_to_repo(repo_root, target_path)
    selection = select_benchmark_for_target(repo_root, relative_target_path)
    manifest = {
        "repo_root": str(repo_root),
        "target_path": str(target_path),
        "relative_target_path": relative_target_path,
        "benchmark_path": selection.benchmark_path,
        "selection_reason": selection.reason,
        "build_command": list(BUILD_COMMAND),
        "build_capability": build_capability_payload(repo_root),
        "prepared_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z"),
        "source_metrics": source_metrics(target_path),
    }
    write_json(case_dir / "manifest.json", manifest)
    readme = "\n".join(
        [
            "# DuckDB Campaign Case",
            "",
            f"- target: `{relative_target_path}`",
            f"- benchmark: `{selection.benchmark_path}`",
            f"- selection_reason: `{selection.reason}`",
            "",
            "This case was generated by the DuckDB smoke-test hooks for the campaign controller.",
        ]
    )
    (case_dir / "README.md").write_text(readme + "\n", encoding="utf-8")
    emit_payload(
        {
            "ok": True,
            "target_path": str(target_path),
            "relative_target_path": relative_target_path,
            "benchmark_path": selection.benchmark_path,
            "selection_reason": selection.reason,
        }
    )


if __name__ == "__main__":
    main()
